### ISSUE TITLE
1.0.6 and 1.0.5 not installable via pip?

### ISSUE THREAD

**Issue by eMerzh** [gaelen/python-statsd-client#4]
Hi, 

not really sure it's something you can do, but i was trying to install 1.0.6 but it seems that only 1.0.4 is available via pip.

could you update that ? so i can benefit from py3 fixes ? 

Thanks for your great work 👍

**Comment by eMerzh** [comment]
ping @gaelen  ?

**Comment by gaelen** [comment]
Fixed.  I thought it had uploaded but I guess pypi changed their API, so my hook didn't push when the release was registered.
